### ISSUE TITLE
Plugin breaks my links because of one [

### ISSUE THREAD

**Issue by sirlaughalot90** [val3344/obsidian-update-relative-links#2]
Hi,

I experience an issue which breaks links in the process of converting them because it transforms them from [[note title]] to [[note title](link). So it is not a big issue, just one [ too much in the beginning, yet it has enormous consequences. 

Any way to fix this, besides manual labor? 😅

**Comment by val3344** [comment]
> ## Plugin restrictions
>
> The `Use [[Wikilinks]]` option must be turned off to use Markdown's link syntax. The point of using relative paths is also to make notes more generic, and if you are also using Wiki Links, there is no need to use relative paths.

First confirm the constraints mentioned in the [README](https://github.com/val3344/obsidian-update-relative-links#plugin-restrictions), this plugin does not intend to support `[[Wikilinks]]`. Because the original purpose of using relative paths is to make notes more generic, but `[[Wikilinks]]` is not standard Markdown syntax. You can check if `Settings -> Files & Links -> Use [[Wikilinks]]` is turned off, like this:

![image](https://user-images.githubusercontent.com/11001285/195616325-03c6e3bc-a810-4448-9f16-c21fdfdc59c5.png)

But even with this switch on, I still haven't been able to reproduce the problem you describe. Can you provide more detailed steps to reproduce?

**Comment by miermontoto** [comment]
when converting wikilinks into relative paths with this plugin, the double `[` symbol is ignored, causing links to appear distorted and breaking compatibility with some syntax readers and visualizers (such as previewing MD files in GitHub).

![image](https://github.com/val3344/obsidian-update-relative-links/assets/20926603/2c14e6ed-3cff-466c-b9f2-2e2047afb729)

even when turning the wikilinks option off, they aren't automatically updated, so there is no way to convert all wikilinks to regular markdown files in order for this extension to work.

**Comment by val3344** [comment]
This plugin does not have the functionality to convert WikiLinks (`[[WikiLinks]]`) to Markdown link (`[title](path)`). I checked the logic of the plugin and it only replaces the link text and doesn't handle symbols like `[]()` etc. And I tested the following use case for WikiLinks:

```
[[b/a.md|a]]
```

The plugin can correctly convert it into:

```
[[a.md|a]]
```

It is still WikiLinks and will not be converted to Markdown link, so please confirm whether you are using other plugins?
