### ISSUE TITLE
[Feature Request] Update Link Text

### ISSUE THREAD

**Issue by sigrunixia** [val3344/obsidian-update-relative-links#3]
Hello!

I am enjoying the functionality of your add-on. As someone who is still moving around and combining their vaults, and will be doing so for the foreseeable future, the time savings this plugin has given me has been noticeable. There is one quality of life change that remains that I am wondering if it could be addressed by adding some additional.

## Situation

Moving notes around (whether though needing to move, or using templates scripts to move, seems to be creating the following naming convention in linked notes.

`[../18 Zettel People/Carolyn Whitson PhD](../18%20Zettel%20People/Carolyn%20Whitson%20PhD.md)`

The links lose their original titles, and even ignore aliases if I link to the alias. I have read on Obsidian.md's forums that others have experienced the same and its a longstanding issue. 

### What I'd like to see

I'd like to see the plugin, if possible, be able to correct these links back to either a local note name, an alias, a title, or perhaps even a user specified YAML front matter entry. 

`[Carolyn Whitson](../18%20Zettel%20People/Carolyn%20Whitson.md)`

Right now I am accomplishing this by using an external text editor, but it is a reoccurring task.

**Comment by val3344** [comment]
`[../18 Zettel People/Carolyn Whitson PhD](../18%20Zettel%20People/Carolyn%20Whitson%20PhD.md)`

Can you describe how the link was generated?

If I have the following directory structure:

```txt
dir-a/
└── file-a.md
file-b.md
```

Then inserting the link to `file-a.md` in `file-b.md`, I get `[file-a](dir-a/file-a.md)` instead of `[dir-a/file-a.md](dir-a/file-a.md)`.

So I don't know how this link was generated: `[../18 Zettel People/Carolyn Whitson PhD](../18%20Zettel%20People/Carolyn%20Whitson%20PhD.md)`.
